"""Generate Pydantic v2 models from the OpenAPI spec into src/pulse/vbr/models/generated.py.

    uv run python scripts/gen_models.py            # full regeneration (~5 min)
    uv run python scripts/gen_models.py --fix-only # re-run only the post-processing

Post-processing: the VBR spec declares discriminators whose subtype fields are
enums rather than single-value literals, which Pydantic refuses. We drop the
`discriminator=` hints so those fields become plain (smart-mode) unions.
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPEC = ROOT / "openapi" / "vbr-1.3-rev2.json"
OUT = ROOT / "src" / "pulse" / "vbr" / "models" / "generated.py"

CODEGEN_ARGS = [
    "--input",
    str(SPEC),
    "--input-file-type",
    "openapi",
    "--output",
    str(OUT),
    "--output-model-type",
    "pydantic_v2.BaseModel",
    "--target-python-version",
    "3.12",
    "--use-standard-collections",
    "--use-union-operator",
    "--field-constraints",
    "--use-annotated",
    "--use-double-quotes",
    "--disable-timestamp",
    "--capitalise-enum-members",
    "--custom-file-header",
    "# GENERATED by scripts/gen_models.py from openapi/vbr-1.3-rev2.json. Do not edit by hand.",
]

_DISCRIMINATOR = re.compile(r',?\s*discriminator="[^"]+"(\s*,)?')


def _strip_discriminator(match: re.Match[str]) -> str:
    # Keep one separating comma when the hint sat between two other arguments.
    return "," if match.group(0).startswith(",") and match.group(1) else ""


def fix(text: str) -> tuple[str, int]:
    return _DISCRIMINATOR.subn(_strip_discriminator, text)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--fix-only", action="store_true")
    args = parser.parse_args()

    if not args.fix_only:
        subprocess.run(  # noqa: S603 - fixed argv
            [sys.executable, "-m", "datamodel_code_generator", *CODEGEN_ARGS], check=True
        )
    text, count = fix(OUT.read_text(encoding="utf-8"))
    OUT.write_text(text, encoding="utf-8")
    print(f"Removed {count} discriminator hints from {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
