"""Generate src/pulse/vbr/operations.py from the OpenAPI spec.

Maps every operationId to (method, path, tag) so the client never hand-types a path.

    uv run python scripts/gen_operations.py
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPEC = ROOT / "openapi" / "vbr-1.3-rev2.json"
OUT = ROOT / "src" / "pulse" / "vbr" / "operations.py"

HTTP_METHODS = ("get", "post", "put", "patch", "delete")

HEADER = '''"""operationId -> (method, path, tag) for VBR REST API {version}.

GENERATED by scripts/gen_operations.py from {spec}. Do not edit by hand.
"""

from __future__ import annotations

from typing import NamedTuple

SPEC_VERSION = "{version}"
DOCS_ROOT = "https://helpcenter.veeam.com/references/vbr/13/rest/{version}"


class Operation(NamedTuple):
    operation_id: str
    method: str
    path: str
    tag: str

    @property
    def docs_url(self) -> str:
        return f"{{DOCS_ROOT}}/tag/{{self.tag.replace(' ', '-')}}#operation/{{self.operation_id}}"


OPERATIONS: dict[str, Operation] = {{
'''


def main() -> None:
    spec = json.loads(SPEC.read_text(encoding="utf-8"))
    version = spec["info"]["version"]
    rows: list[tuple[str, str, str, str]] = []
    for path, item in spec["paths"].items():
        for method in HTTP_METHODS:
            op = item.get(method)
            if not op or "operationId" not in op:
                continue
            tags = op.get("tags") or ["Untagged"]
            rows.append((op["operationId"], method.upper(), path, tags[0]))

    ids = [r[0] for r in rows]
    dupes = {i for i in ids if ids.count(i) > 1}
    if dupes:
        raise SystemExit(f"Duplicate operationIds in spec: {sorted(dupes)}")

    lines = [HEADER.format(version=version, spec=SPEC.relative_to(ROOT).as_posix())]
    for op_id, method, path, tag in sorted(rows):
        lines.append(f"    {op_id!r}: Operation({op_id!r}, {method!r}, {path!r}, {tag!r}),\n")
    lines.append("}\n")
    OUT.write_text("".join(lines), encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} with {len(rows)} operations")


if __name__ == "__main__":
    main()
